import type { VocabWord } from "./vocab";

// 단어B (Day 1~10, 400 단어) — 원본 예문 그대로
export const vocabB: VocabWord[] = [
  // ── Day 1 ──────────────────────────────────────────────────
  { english: "assemble", korean: "조립하다, 모이다", sentence: "Industrial equipment is being assembled." },
  { english: "develop", korean: "개발하다, 성장하다", sentence: "The first place winner will be given the chance to develop a new game." },
  { english: "operate", korean: "작동하다, 운영하다", sentence: "He showed workers how to operate the new machinery." },
  { english: "productivity", korean: "생산성", sentence: "We hope that our new manufacturing system will increase productivity." },
  { english: "research", korean: "연구, 조사", sentence: "The research on this matter is still inconclusive." },
  { english: "devise", korean: "고안하다, 생각해내다", sentence: "The task force was urged to devise an alternative solution." },
  { english: "durable", korean: "내구성이 좋은", sentence: "Generally, German cars are considered much more durable." },
  { english: "prove", korean: "입증하다, 증명하다", sentence: "Just give me a chance and I'll prove it to you." },
  { english: "enhance", korean: "향상시키다, 강화하다", sentence: "To enhance building appearances, computer design technology was utilized throughout the entire construction." },
  { english: "quality", korean: "품질, 고급의", sentence: "We should concentrate on the quality control to increase our market share." },
  { english: "reliable", korean: "신뢰할 수 있는", sentence: "We need a reliable person for the managerial position." },
  { english: "safety", korean: "안전, 안전성", sentence: "Lab technicians are required to wear protective gear for safety reasons." },
  { english: "allow", korean: "허락하다, 허용하다", sentence: "This automatic system will allow us to work efficiently." },
  { english: "equipment", korean: "장비, 설비", sentence: "Each piece of heavy equipment must be inspected before each day of use." },
  { english: "search", korean: "조사, 검색", sentence: "The search for alternative energy sources will never stop." },
  { english: "inspect", korean: "조사하다, 검사하다", sentence: "We have a plan to inspect agricultural products." },
  { english: "intend", korean: "의도하다, ~하려하다", sentence: "The store intended to pay for the defects." },
  { english: "solution", korean: "해결책, 해법", sentence: "We have yet to find a solution to the current poverty issue." },
  { english: "material", korean: "재료, 자료", sentence: "Do you have time to review our presentation material?" },
  { english: "expectation", korean: "예상, 기대", sentence: "The design of the new product was beyond my expectations." },
  { english: "resource", korean: "자원", sentence: "Oil is the most important natural resource to human beings." },
  { english: "functional", korean: "작동되는, 기능의", sentence: "The central heating will soon be functional." },
  { english: "generate", korean: "창출하다, 발생시키다", sentence: "Please be advised that our objective is to generate profits with trusted assets." },
  { english: "discontinue", korean: "중단하다", sentence: "Waterway Co. discontinued car washing services." },
  { english: "comparable", korean: "필적할만한", sentence: "Our prices are comparable to those at big stores." },
  { english: "halt", korean: "중단시키다, 멈추다", sentence: "Production will be halted next month." },
  { english: "complicated", korean: "복잡한, 까다로운", sentence: "Today, we will handle a sensitive and complicated issue." },
  { english: "estimate", korean: "추정하다, 견적을 내다", sentence: "They estimated the value of the building." },
  { english: "invent", korean: "고안하다, 발명하다", sentence: "Our engineers invented a computerized inventory system." },
  { english: "feasible", korean: "실현 가능한", sentence: "A newcomer suggested a financially feasible plan for the project." },
  { english: "customized", korean: "맞춤식의, 주문제작된", sentence: "We offer customized services to improve our customers' satisfaction." },
  { english: "automate", korean: "자동화하다", sentence: "In order to save time, the company decided to automate all of its operations." },
  { english: "pertinent", korean: "적절한, 관련 있는", sentence: "All information pertinent to the proposal should be sent to me." },
  { english: "inspiration", korean: "영감", sentence: "The designer drew inspiration from the old painting." },
  { english: "manufacture", korean: "제조하다, 생산하다", sentence: "The manufacturing process will be monitored thoroughly." },
  { english: "merit", korean: "장점", sentence: "This laptop has a number of merits." },
  { english: "patent", korean: "특허(권)", sentence: "We got a patent for the new technology." },
  { english: "persist", korean: "계속하다, 지속되다", sentence: "Economists anticipate that the high unemployment rate will persist for a long time." },
  { english: "prototype", korean: "원형, 시제품", sentence: "I'm concerned about the budget to develop the prototype." },
  { english: "sequence", korean: "연속, 순서, 차례", sentence: "I described the sequence of events beforehand." },

  // ── Day 2 ──────────────────────────────────────────────────
  { english: "customer", korean: "고객, 손님", sentence: "New customers are eligible for discounts." },
  { english: "bill", korean: "청구하다, 청구서", sentence: "Christine will be billed 10 dollars for her subscription." },
  { english: "handle", korean: "다루다, 처리하다", sentence: "Mr. Halley's duty is handling calls from customers." },
  { english: "reach", korean: "도착하다, ~에 달하다", sentence: "The management tried to reach an agreement with the labor union within this week." },
  { english: "inquire", korean: "문의하다, 조사하다", sentence: "It's forbidden to inquire about personal information of customers." },
  { english: "confuse", korean: "혼란스럽게하다, 혼동하다", sentence: "The new guidelines confuse everyone, so we need to fix them." },
  { english: "valid", korean: "유효한, 타당한", sentence: "A valid receipt must be presented to be reimbursed for the expense." },
  { english: "deal", korean: "거래, 다루다", sentence: "We had a good deal on the hotel reservation for the conference." },
  { english: "respond", korean: "반응하다, 응답하다", sentence: "It's essential for us to respond to customer complaints." },
  { english: "regular", korean: "정기적인, 규칙적인", sentence: "The physician encouraged me to exercise on a regular basis." },
  { english: "complaint", korean: "불평, 불만", sentence: "Dream Company actively responds to customer complaints." },
  { english: "renewal", korean: "갱신, 재개발", sentence: "Please check the renewal date on the contract." },
  { english: "available", korean: "이용 가능한, 시간이 있는", sentence: "Tickets are available at the 15th Street Theater box office." },
  { english: "address", korean: "처리하다, 연설하다", sentence: "The mayor addressed an audience." },
  { english: "questionnaire", korean: "설문지", sentence: "Before we end today's meeting, I'd like to ask you to complete the questionnaire." },
  { english: "free", korean: "자유로운, 무료의", sentence: "I have attached a printable coupon for a free meal at our hotel restaurant." },
  { english: "protect", korean: "보호하다, 지키다", sentence: "Safety helmets will protect workers from danger." },
  { english: "disappoint", korean: "실망시키다", sentence: "Declining sales in North America disappointed many shareholders." },
  { english: "guarantee", korean: "보장하다, 보증하다", sentence: "This device is guaranteed against all defects for a period of one year." },
  { english: "hesitate", korean: "망설이다, 주저하다", sentence: "Should you have any questions, please do not hesitate to contact us." },
  { english: "willing", korean: "기꺼이 하는, 자발적인", sentence: "We are always willing to provide customers with the best service we can." },
  { english: "basis", korean: "기준, 기초, 근거", sentence: "Tickets will be allocated on a first-come, first-served basis, please hurry." },
  { english: "satisfaction", korean: "만족, 충족", sentence: "She looked over the report with great satisfaction." },
  { english: "interact", korean: "상호 작용하다, 소통하다", sentence: "We haven't interacted with other people so often." },
  { english: "politely", korean: "공손하게, 정중하게", sentence: "You need to speak with customers politely." },
  { english: "retain", korean: "유지하다, 보유하다", sentence: "Don't forget to retain your ticket stub to enter the contest." },
  { english: "insert", korean: "삽입하다, 넣다", sentence: "The sales clerk inserted some leaflets into an envelope to provide me with more information." },
  { english: "critical", korean: "비판적인, 중요한", sentence: "Retaining high-quality employees is critical to the growth of the company." },
  { english: "react", korean: "반응하다, 대처하다", sentence: "Our sales representatives are trained to react promptly to customer complaints." },
  { english: "further", korean: "추가의, 더 나아가", sentence: "Mr. Weinstein transferred to the sales department to further his career." },
  { english: "cordially", korean: "진심으로, 정성껏", sentence: "We cordially apologize for the poor service." },
  { english: "disclose", korean: "밝히다, 폭로하다", sentence: "Public institutions must disclose their financial details." },
  { english: "consignment", korean: "위탁 판매(품)", sentence: "They sell goods on consignment." },
  { english: "genuine", korean: "진짜의, 진품의", sentence: "A customer is looking for a jacket made of genuine leather." },
  { english: "thoroughly", korean: "철저하게, 대단히", sentence: "The mechanic will inspect the car thoroughly." },
  { english: "instant", korean: "즉각적인, 순간", sentence: "This card gives you instant access to the database." },
  { english: "courteous", korean: "예의 바른, 정중한", sentence: "A courteous and well-trained waiter will escort you to breakfast." },
  { english: "pledge", korean: "약속, 서약", sentence: "The charity group has pledged its support to build the children's hospital." },
  { english: "preliminary", korean: "예비의, 사전의", sentence: "The marketing team will conduct a preliminary survey tomorrow." },
  { english: "quota", korean: "할당(량), 한도", sentence: "We need to secure this contract to meet the sales quota." },

  // ── Day 3 ──────────────────────────────────────────────────
  { english: "defective", korean: "결함이 있는", sentence: "Generally, stores give customers refunds for defective items." },
  { english: "contact", korean: "연락하다, 접촉", sentence: "I contacted all of our established customers to inform them of an upcoming change." },
  { english: "repair", korean: "수리하다, 고치다", sentence: "The maintenance department will dispatch a technician to repair the elevator immediately." },
  { english: "damage", korean: "손상을 주다, 피해", sentence: "The building was badly damaged by the fire." },
  { english: "completely", korean: "완전히, 전적으로", sentence: "Entry forms must be filled out completely in order for individuals to be eligible to win the cash prize drawing." },
  { english: "observe", korean: "관찰하다, 준수하다", sentence: "The safety inspector observed the whole production process thoroughly." },
  { english: "disposable", korean: "일회용의", sentence: "Environmental groups require people to reduce the use of disposable products." },
  { english: "status", korean: "상태, 상황, 지위", sentence: "Our new system enables us to track the status of shipment 24 hours a day." },
  { english: "receipt", korean: "영수증", sentence: "You should bring the original receipt to get a refund." },
  { english: "warranty", korean: "보증, 보증서", sentence: "The laptop computer comes with a three-year warranty." },
  { english: "confirmation", korean: "확인, 확증", sentence: "You will receive a confirmation e-mail to verify your registration." },
  { english: "aware", korean: "인지하고 있는, 알고 있는", sentence: "Please be aware that your subscription will expire on May 31." },
  { english: "expiration", korean: "만료, 만기", sentence: "Please check the expiration date of your credit card." },
  { english: "flaw", korean: "결함", sentence: "The warranty covers minor damage by daily use and manufacturing flaws." },
  { english: "inventory", korean: "재고(품), 재고 목록", sentence: "Why don't we think about ways to decrease our inventory?" },
  { english: "install", korean: "설치하다, 장착하다", sentence: "The computer is being installed in an office." },
  { english: "maintain", korean: "유지하다, 주장하다", sentence: "To maintain your health, you should work out regularly." },
  { english: "method", korean: "방법, 방식", sentence: "The new method of analyzing marketing data will be introduced at the seminar." },
  { english: "necessary", korean: "필요한, 필수적인", sentence: "You can download all the necessary documents for the application on the website." },
  { english: "utilize", korean: "활용하다, 이용하다", sentence: "You might want to utilize a website to promote your new store." },
  { english: "state", korean: "상태, 지위, 말하다", sentence: "The state of our country's economy is unstable." },
  { english: "superior", korean: "우수한, 상급의", sentence: "Our new product is technically superior to our competitors' old models." },
  { english: "component", korean: "(구성)요소, 부품", sentence: "We replace worn-out components with new ones at no extra cost." },
  { english: "feature", korean: "특징으로 삼다, 특징", sentence: "The display in the east wing of the history museum will feature artifacts from ancient Greece." },
  { english: "substitute", korean: "대신하다, 대체하다", sentence: "Jim substituted for the vice president who was on vacation." },
  { english: "do business with", korean: "~와 거래하다", sentence: "I would do business with ideal Equipment Rentals again because of their exceptional service." },
  { english: "combination", korean: "조합, 결합", sentence: "The cleaning solution being marketed by Buyman Chemical has to be used in combination with a little water." },
  { english: "investigate", korean: "조사하다, 수사하다", sentence: "The marketing department will investigate how customers make a selection in the market." },
  { english: "malfunction", korean: "기능 장애, 오작동", sentence: "Due to the computer malfunction we couldn't meet the deadline." },
  { english: "at the latest", korean: "늦어도~까지", sentence: "Please make sure that shipments ordered yesterday are delivered by Friday at the latest." },
  { english: "maneuver", korean: "작전, 책략", sentence: "Our competitors try various maneuvers to make profits." },
  { english: "surplus", korean: "흑자, 잉여", sentence: "The management hasn't decided how to deal with a massive budget surplus." },
  { english: "verify", korean: "확인하다, 입증하다", sentence: "We should verify your identification to let you in." },
  { english: "alteration", korean: "변경, 개조", sentence: "The sales advisor has sent letters to all branches alerting them to the newest alteration in the market." },
  { english: "diversify", korean: "다각화하다, 다양해지다", sentence: "We are determined to diversify our products to expand the customer base." },
  { english: "appliance", korean: "(가정용)기기, 가전제품", sentence: "The company always offers home appliances at reasonable prices." },
  { english: "array", korean: "배열", sentence: "Nathan felt a wide array of emotions when he handled a demanding customer." },
  { english: "recall", korean: "회수하다, 기억하다", sentence: "GT motors announced a recall of all the models." },
  { english: "commodity", korean: "상품, 물품", sentence: "Even though the economy is getting worse, sales in the luxury commodities have been increasing." },
  { english: "struggle", korean: "애쓰다", sentence: "We struggle to keep the business afloat." },

  // ── Day 4 ──────────────────────────────────────────────────
  { english: "pick up", korean: "물건을 찾아오다, 들어 올리다", sentence: "You should pick up the order form and fill it out now." },
  { english: "delivery", korean: "배달(품)", sentence: "Our special delivery service will keep track of the shipment and let customers know when they will receive their orders." },
  { english: "refund", korean: "환불하다, 환불(금)", sentence: "You can get a cash refund for defective items within 50 days of purchase." },
  { english: "distribute", korean: "배포하다, 유통시키다", sentence: "The new product brochures will be distributed at the Consumer Electronics Show." },
  { english: "shipment", korean: "선적(물), 배송(품)", sentence: "The shipment was delivered on time." },
  { english: "express", korean: "표현하다, 급행의", sentence: "We would like to express our appreciation for your help." },
  { english: "accidentally", korean: "우연히, 뜻하지 않게", sentence: "A discount voucher was accidentally sent to the wrong address." },
  { english: "measure", korean: "조치, 대책, 측정하다", sentence: "The government ought to take appropriate measures to protect citizens from violent crimes." },
  { english: "individually", korean: "개별적으로, 각각 따로", sentence: "Roses can be purchased individually for $5, or one dozen for $55." },
  { english: "convenience", korean: "편의(시설), 편리함", sentence: "Please let me know whether you want to contact me by telephone or e-mail at your earliest convenience." },
  { english: "export", korean: "수출하다, 수출(품)", sentence: "Smithson Apparel exports a wide variety of fashion items from clothes to shoes." },
  { english: "valuable", korean: "가치 있는, 귀중한", sentence: "Ms. Brooks proved herself as a valuable asset to our company." },
  { english: "invoice", korean: "송장, 청구서", sentence: "The accurate invoice number should be entered to track the process of shipments." },
  { english: "container", korean: "용기, 컨테이너", sentence: "Florida Orange Company uses trucks with refrigerated containers to keep oranges from spoiling." },
  { english: "fix", korean: "고정시키다, 수리하다", sentence: "The repairman fixed a shelf on the wall." },
  { english: "track", korean: "추적하다", sentence: "They couldn't track the delivery of the returned items." },
  { english: "separately", korean: "분리하여, 개별적으로", sentence: "Some office supplies you ordered will be shipped separately." },
  { english: "caution", korean: "주의를 주다, 경고", sentence: "The immediate supervisor cautioned his staff against being late to the seminar." },
  { english: "simplify", korean: "단순화하다, 간단히 하다", sentence: "A tax refund form will be simplified soon." },
  { english: "acknowledge", korean: "인정하다, 받았음을 알리다", sentence: "I sent an e-mail to acknowledge receipt of the payment." },
  { english: "domestic", korean: "국내의, 가정(용)의", sentence: "Besides managing the domestic sales team, Mr. Goodvin has been giving advice to the international sales department." },
  { english: "package", korean: "짐, 소포, 포장", sentence: "The courier service delivered a package to the wrong address by mistake." },
  { english: "label", korean: "라벨, 라벨을 붙이다", sentence: "The label should be attached on the lid." },
  { english: "dispatch", korean: "발송하다, 보내다", sentence: "Your order will be dispatched without delay." },
  { english: "fragile", korean: "깨지기 쉬운", sentence: "Employees should pack the fragile products very cautiously." },
  { english: "freight", korean: "화물(운송)", sentence: "We recommend the express freight service if customers want their merchandise received in a timely manner." },
  { english: "storage", korean: "저장(소), 보관(시설)", sentence: "The workers are moving boxes into the storage facility at the port." },
  { english: "content", korean: "내용(물), 만족한", sentence: "Didn't you check the content of shipments?" },
  { english: "carton", korean: "(음식, 음료를 담는)곽(통)", sentence: "Some cartons have been piled on the floor." },
  { english: "quantity", korean: "양, 수량", sentence: "The store is stocked with a large quantity of electronic goods." },
  { english: "transport", korean: "수송하다, 운반하다", sentence: "Containers are being transported to the warehouse." },
  { english: "stringent", korean: "(법률, 규칙 등이)엄격한", sentence: "All of the medical products imported to Korea must comply with stringent regulations." },
  { english: "pending", korean: "미결정의, 현안의", sentence: "The pending problems between the two companies should be dealt with cautiously." },
  { english: "recipient", korean: "수령인, 수취인", sentence: "The recipient's name and address should be printed on the label attached to the package." },
  { english: "exempt", korean: "면제된", sentence: "Any domestic order valued at $150 or more is exempt from delivery charges." },
  { english: "courier", korean: "택배, 배달원", sentence: "You'd better use courier services to send this parcel." },
  { english: "expedite", korean: "신속히 처리하다, 촉진하다", sentence: "Claire asked the store to expedite her orders." },
  { english: "agency", korean: "대행 회사, 대리점", sentence: "We hired a competitive advertising agency to implement a more aggressive marketing strategy." },
  { english: "affix", korean: "붙이다, 부착하다", sentence: "The price tag was firmly affixed to the items." },
  { english: "postage", korean: "우편 요금", sentence: "Please check the postage for air mail." },

  // ── Day 5 ──────────────────────────────────────────────────
  { english: "expect", korean: "예상하다, 기대하다", sentence: "Sales are expected to reach $30 million thanks to the innovative marketing strategies." },
  { english: "target", korean: "목표, 겨냥하다", sentence: "We should focus on our target audience." },
  { english: "affect", korean: "영향을 미치다", sentence: "Marketing specialists are not sure how changes in the climate will affect sales of recreational vehicles." },
  { english: "description", korean: "기술서, 서술", sentence: "Free copies of the product descriptions are now available at any of our stores in the country." },
  { english: "demand", korean: "요구하다, 수요", sentence: "As the demand is increasing, the sales are expected to rise drastically for the next few years." },
  { english: "focus", korean: "초점을 두다, 집중하다", sentence: "The first phase of the project focused on creating a main menu comprised of frequent customer inquiries." },
  { english: "launch", korean: "출시하다, 시작하다", sentence: "They plan to launch a new line of footwear this winter." },
  { english: "majority", korean: "대부분, 과반수", sentence: "The majority of the employees are in favor of the new dress code." },
  { english: "device", korean: "장치", sentence: "SAN Electronics' newly marketed auto cleaning device is reported to be far superior to its previous one." },
  { english: "provide", korean: "제공하다, 공급하다", sentence: "Our website will provide you with more details about it." },
  { english: "survey", korean: "(설문)조사, 검사", sentence: "We will conduct a survey to get some feedback from our customers." },
  { english: "trade", korean: "무역, 거래, 교환하다", sentence: "The 5th trade fair will be held in London." },
  { english: "introduce", korean: "소개하다, 발표하다", sentence: "We plan to introduce our new product line at the conference." },
  { english: "complimentary", korean: "무료의", sentence: "The package tour to Chile includes a complimentary wine tasting." },
  { english: "lack", korean: "부족, 결핍", sentence: "Our company suffers from a lack of money." },
  { english: "flyer", korean: "(광고용)전단", sentence: "Present this flyer and you will receive your choice of a free appetizer or dessert." },
  { english: "demonstration", korean: "설명, 시연", sentence: "The three-day seminar will be filled with demonstrations of accounting software, small group sessions, and more." },
  { english: "influence", korean: "영향, 영향을 주다", sentence: "The new TV commercial has had a positive influence on our target consumers." },
  { english: "initial", korean: "처음의, 초기의", sentence: "My initial plan was to hire five part-time workers for the peak season." },
  { english: "publicity", korean: "홍보, 광고", sentence: "Our new line of vehicles did not receive much publicity but sales went up quickly." },
  { english: "regardless of", korean: "~와 관계없이", sentence: "We should win the bid regardless of cost." },
  { english: "steep", korean: "급격한, 가파른", sentence: "The steep decline in sales resulted in the recent drop of our stock price." },
  { english: "analysis", korean: "분석, 검토", sentence: "Your answers to these questionnaires are critical for our market analysis." },
  { english: "numerous", korean: "많은", sentence: "This gadget has numerous advanced features." },
  { english: "principal", korean: "주요한, 주된", sentence: "The principal reason for price drops is the lack of demand." },
  { english: "claim", korean: "(권리를)주장하다, 청구하다", sentence: "Small companies always claim that their products are not inferior to those of major companies." },
  { english: "consecutive", korean: "연이은, 연속적인", sentence: "Trendy Minds has won the Dream Marketing Award for five consecutive years." },
  { english: "accurately", korean: "정확히, 정밀하게", sentence: "Clerks should enter client data accurately by tomorrow." },
  { english: "contrary", korean: "반대되는, 반대의", sentence: "Don't act contrary to your conscience." },
  { english: "especially", korean: "특히", sentence: "Only use oil-based cleaners especially designed for this surface." },
  { english: "yield", korean: "산출하다, 생산량", sentence: "Her analysis yielded valuable information for our business plan." },
  { english: "enormous", korean: "엄청난, 막대한", sentence: "Thanks to the hard work of our committed workers, we have achieved enormous success in the market." },
  { english: "exaggerate", korean: "과장하다", sentence: "Demand for the newly launched product has been highly exaggerated." },
  { english: "speculation", korean: "추측, 짐작", sentence: "His resignation received much speculation from employees." },
  { english: "collective", korean: "집단의, 공동의", sentence: "The sales promotion event was successfully held by collective effort." },
  { english: "versatile", korean: "다재다능한, 다용도의", sentence: "We will participate in the job fair to look for versatile candidates." },
  { english: "aggressively", korean: "적극적으로, 공격적으로", sentence: "The food conglomerate aggressively promoted their new frozen food." },
  { english: "dealership", korean: "(판매)대리점", sentence: "We are the only dealership in the region that carries replacement parts for all of our vehicles." },
  { english: "stability", korean: "안정(성), 지속", sentence: "The equilibrium of demand and supply resulted in the economic stability." },
  { english: "substantial", korean: "상당한, 충분한", sentence: "Due to your dedication and hard work, our firm has experienced substantial growth." },

  // ── Day 6 ──────────────────────────────────────────────────
  { english: "commercial", korean: "광고, 상업적인", sentence: "Any commercial transaction within the country will be monitored by the committee." },
  { english: "strategy", korean: "전략, 계획, 방법", sentence: "Let's call a meeting to develop a new marketing strategy." },
  { english: "consistently", korean: "끊임없이, 항상", sentence: "To stay consistently productive, taking short breaks throughout the day will be helpful." },
  { english: "release", korean: "발표하다, 출시하다", sentence: "Our new fax machines will be released at the end of the year." },
  { english: "stock", korean: "주식, 재고, 채우다", sentence: "I'm afraid that these items are currently out of stock." },
  { english: "affordable", korean: "(가격이)알맞은, 감당 할 수 있는", sentence: "Our aim is to lower prices to make products more affordable for consumers." },
  { english: "representative", korean: "대표자, 대리인", sentence: "The personnel manager interviewed some prospective sales representatives." },
  { english: "await", korean: "기다리다", sentence: "Ms. Jones found the eagerly awaited novel had been published." },
  { english: "display", korean: "전시하다, 진열(품)", sentence: "Visitors are prohibited from taking photographs of any exhibits displayed in the museum." },
  { english: "indicate", korean: "나타내다, 보여주다", sentence: "The results of the survey indicate that young customers prefer blue over red." },
  { english: "aim", korean: "목표하다, 겨냥하다", sentence: "Our new line of handbags is aimed at women between the ages of 20 and 30." },
  { english: "extremely", korean: "극도로, 대단히", sentence: "This new line of refrigerators is extremely good at regulating the inside temperature." },
  { english: "priority", korean: "우선(권), 우위", sentence: "Your safety is our priority during the tour." },
  { english: "compare", korean: "비교하다", sentence: "The sales figures have improved about 15% compared with last quarter." },
  { english: "creative", korean: "창의적인", sentence: "It was Sharon's work on the creative car design that won her the lifetime excellence award." },
  { english: "closely", korean: "밀접하게, 면밀하게", sentence: "There is a rumor that he is closely related to the credit card fraud." },
  { english: "independent", korean: "독립적인, 독자적인", sentence: "CCG is an independent organization that oversees commercial transactions among government agencies." },
  { english: "surpass", korean: "초과하다, 능가하다", sentence: "Surprisingly the annual sales surpassed my initial expectation." },
  { english: "orderly", korean: "질서 정연한, 정돈된", sentence: "In case of a fire, please exit the building in an orderly manner." },
  { english: "streamline", korean: "간소화하다, 합리화하다", sentence: "Shouldn't we streamline the current production process?" },
  { english: "practical", korean: "실용적인, 실현 가능한", sentence: "We should work together to address these practical problems." },
  { english: "trial", korean: "시험, 실험, 시도", sentence: "You are welcome to return after a 30-day trial period." },
  { english: "comment", korean: "논평하다, 언급하다", sentence: "He refused to comment on the bribery scandal." },
  { english: "vendor", korean: "판매자, 노점, 행상(인)", sentence: "There are a number of vendors in the street market." },
  { english: "existing", korean: "기존의, 현존의", sentence: "The conclusion was that repairing the existing machines cost much more than buying new ones." },
  { english: "call on", korean: "요청하다, 부탁하다", sentence: "We called on the professor to speak at the graduation ceremony." },
  { english: "clearance", korean: "(재고)정리", sentence: "During the spring seasons every year, Grada grocery store holds a clearance sale." },
  { english: "peak", korean: "절정, 최고점, 절정기의", sentence: "The exchange rate reached its peak yesterday and started to go down today." },
  { english: "quote", korean: "인용하다, 견적을 내다", sentence: "The architectural firm quoted us a million dollars for renovating the building." },
  { english: "solely", korean: "오로지, 단독으로", sentence: "In fact, I'm solely responsible for this project." },
  { english: "stimulate", korean: "자극하다, 촉진시키다", sentence: "To stimulate the economy, the government decided to ease some restrictions." },
  { english: "dispense", korean: "나누어 주다, 제공하다", sentence: "This vending machine dispenses mineral water, snacks and beverages." },
  { english: "endorse", korean: "홍보하다, 배서하다", sentence: "An actress who is a former beauty queen endorsed the new makeup line." },
  { english: "testimonial", korean: "증명서, 추천장", sentence: "You can check more testimonials from our consumers on the website." },
  { english: "tailored", korean: "맞추어진, 주문 제작의", sentence: "His new designs are well tailored to our customers' taste." },
  { english: "apprehensive", korean: "우려하는", sentence: "The management was apprehensive about possible strikes among the factory workers." },
  { english: "rebate", korean: "환급, 환불", sentence: "You should log onto the website for a tax rebate." },
  { english: "publicize", korean: "홍보하다, 알리다", sentence: "The author is holding a book signing to publicize his new novel." },
  { english: "lapse", korean: "실수, (시간의)경과, 소멸되다", sentence: "The plant manager found a lapse in quality control." },
  { english: "unveil", korean: "베일을 벗다, 발표하다", sentence: "Our concept car will be unveiled at Detroit Auto Show." },

  // ── Day 7 ──────────────────────────────────────────────────
  { english: "anticipate", korean: "예상하다, 기대하다", sentence: "While company officials anticipate layoffs next quarter, they are unsure how large those layoffs will be." },
  { english: "depression", korean: "경기침체, 불황", sentence: "Edward doubled his sales last month in spite of the depression." },
  { english: "financial", korean: "금융의, 금전상의", sentence: "All financial analysts should participate in the conference next week." },
  { english: "rapidly", korean: "빨리, 신속히", sentence: "Blue Pacific has rapidly grown in the industry." },
  { english: "rate", korean: "비율, 요금, 평가하다", sentence: "A long-lasting recession is regarded as the cause of the high unemployment rate." },
  { english: "overview", korean: "개관, 기요", sentence: "Let me give you a quick overview of my presentation." },
  { english: "potential", korean: "잠재적인, 가능성", sentence: "You should take the risk of the potential losses to enter a new market." },
  { english: "predict", korean: "예측하다, 전망하다", sentence: "The renowned economist predicts that the rate of inflation will stabilize at 2% or so." },
  { english: "including", korean: "~을 포함하여", sentence: "The cost for a room is $50 per night including taxes and other fees." },
  { english: "market", korean: "시장, 광고하다", sentence: "It's time for us to expand into the Chinese market." },
  { english: "dramatically", korean: "급격히, 극적으로", sentence: "The sales figure has dramatically increased since last year." },
  { english: "neither", korean: "(둘 중) 어느것도 아닌", sentence: "Neither of the phones is being used at the moment." },
  { english: "opportunity", korean: "기회", sentence: "You will have an opportunity to look around the facilities." },
  { english: "growth", korean: "성장, 증가", sentence: "As oil prices lowered significantly last year, Exon, Inc. is experiencing rapid growth." },
  { english: "drop", korean: "떨어지다, 하락, 감소", sentence: "The temperature is expected to drop to 10 degrees Celsius, with the amount of clouds increasing." },
  { english: "crisis", korean: "위기", sentence: "The board of directors decided to shut down a couple of manufacturing plants due to the current economic crisis." },
  { english: "increase", korean: "증가하다, 증가, 인상", sentence: "We are pleased to announce that profits have increased 30% over the last year." },
  { english: "promising", korean: "전도유망한, 전망이 좋은", sentence: "Most stockholders want the company to invest in the most promising areas for making profits." },
  { english: "obstacle", korean: "장애(물)", sentence: "I'm sure we can overcome any obstacles together." },
  { english: "decline", korean: "감소하다, 거절하다, 하락", sentence: "Sales of our new line of vehicles have declined for the last three months." },
  { english: "boost", korean: "(경기를) 부양하다, 촉진시키다", sentence: "The recent increase in tourism has boosted the local economy in this area." },
  { english: "opposition", korean: "반대, 경쟁사", sentence: "My proposal was approved without any opposition." },
  { english: "overlook", korean: "간과하다, 내려다보다", sentence: "We shouldn't overlook the steady overseas demand of our dairy products." },
  { english: "downturn", korean: "(매출)감소, (경기)침체", sentence: "The current face value reflects the projected downturn, and it will continue to drop." },
  { english: "significant", korean: "상당한, 중요한", sentence: "A significant number of products turned out to be defective and will be recalled within a month." },
  { english: "booming", korean: "경기가 좋은", sentence: "The booming IT industry was the driving force of economic growth." },
  { english: "simultaneously", korean: "동시에", sentence: "It's very important to handle multiple tasks simultaneously." },
  { english: "slightly", korean: "약간, 조금", sentence: "Our market share in Europe slightly decreased this year." },
  { english: "indicator", korean: "지표, 지수", sentence: "The employment rate is regarded as a key indicator of economic health." },
  { english: "insight", korean: "통찰력, 식견", sentence: "I was surprised at the depth of her insight." },
  { english: "economical", korean: "경제적인, 절약하는", sentence: "In the long view, it might be more economical to buy an electric car." },
  { english: "stagnant", korean: "침체된", sentence: "Analysts gathered to discuss how we could boost the stagnant economy." },
  { english: "recession", korean: "불황, 불경기", sentence: "The overall sales have declined dramatically due to the current recession." },
  { english: "ailing", korean: "(경제가)악화된, 병든", sentence: "The government has been struggling to rebuild the ailing economy and create new jobs." },
  { english: "flourish", korean: "번창하다, 융성하다", sentence: "Despite the recent economic recession, Mr. Benson's apparel business has flourished." },
  { english: "deteriorate", korean: "악화되다", sentence: "Due to deteriorating trading conditions, exporting companies have suffered a setback." },
  { english: "skeptical", korean: "의심하는, 회의적인", sentence: "Most of the employees were skeptical of the building project." },
  { english: "fluctuation", korean: "변동", sentence: "Scientists have been committed to developing an intelligent robot which can predict price fluctuations." },
  { english: "entail", korean: "~을 수반하다", sentence: "Even if it entails a heavy loss, the committee decided to announce the recall on their goods." },
  { english: "prosperity", korean: "번영, 번창", sentence: "The CEO attributed our prosperity to his employees' dedication." },

  // ── Day 8 ──────────────────────────────────────────────────
  { english: "reputation", korean: "명성, 평판", sentence: "It is essential for us to establish a reputation as a first-class manufacturer." },
  { english: "competition", korean: "경쟁(자), 시합", sentence: "It is hard to market our furniture internationally because of severe competition." },
  { english: "agreement", korean: "합의, 동의, 협정", sentence: "To win the bid for the new building agreement, we must compete against several other contractors." },
  { english: "period", korean: "기간, 시기", sentence: "You are allowed to use the accounting software free of charge for a 30-day trial period." },
  { english: "fraud", korean: "사기(죄)", sentence: "He was prosecuted for credit card fraud." },
  { english: "renew", korean: "갱신하다, 새롭게 하다", sentence: "The board of directors decided to renew the contract with JR." },
  { english: "proceed", korean: "진행하다, 추진하다", sentence: "Unfortunately, we are not sure that we can proceed to the next program as planned." },
  { english: "expire", korean: "(계약 등이)만료되다, 끝나다", sentence: "We are sending you this e-mail to remind you that your subscription will soon expire." },
  { english: "perform", korean: "공연하다, 실행하다", sentence: "The world famous musical, 'Peace', will be performed in Asia this summer." },
  { english: "approach", korean: "다가가다, 접근(방식)", sentence: "As the deadline approaches, everyone should work overtime." },
  { english: "persuade", korean: "설득하다, 납득시키다", sentence: "We had to persistently persuade him to attend the workshop." },
  { english: "contract", korean: "계약(서), 계약하다", sentence: "As you are aware, the contract will not be effective until signed by both parties." },
  { english: "found", korean: "설립하다, 세우다", sentence: "Ms. Joan founded a catering company at the age of 25." },
  { english: "locate", korean: "위치시키다, 찾아내다", sentence: "Our main office is located in the middle of the city." },
  { english: "reject", korean: "거부하다, 거절하다", sentence: "The president rejected the new restructuring plan we proposed last week." },
  { english: "management", korean: "경영(진), 관리", sentence: "The management finally decided to implement the new payroll system." },
  { english: "proposal", korean: "제안(서), 제의", sentence: "They turned down our proposal to renovate the parking lot." },
  { english: "bid", korean: "입찰하다, 입찰(서)", sentence: "Before we submit our bid, let's break down the construction costs." },
  { english: "settle", korean: "해결하다, 정착하다", sentence: "We are going to hold another public hearing on Monday to settle the argument." },
  { english: "reveal", korean: "보여주다, 밝히다", sentence: "The marketing department plans to reveal the new strategy in this evening's shareholder's meeting." },
  { english: "merge", korean: "합병하다, 통합하다", sentence: "The representatives began negotiations to merge both companies." },
  { english: "finalize", korean: "마무리 짓다, 완결하다", sentence: "City council members will meet next week to finalize the plans." },
  { english: "adversity", korean: "역경, 고난", sentence: "The new vice president turned our company's adversity into an opportunity." },
  { english: "prospective", korean: "잠재적인, 기대되는", sentence: "We will take part in the trade show to find prospective buyers." },
  { english: "established", korean: "평판이 좋은, 확립된", sentence: "It is a pleasure to do business with an established company." },
  { english: "constant", korean: "끊임없이, 지속적인", sentence: "To reflect the constant customer feedback, the company conducts focus group interviews on a regular basis." },
  { english: "phase", korean: "단계, 국면", sentence: "We spent a lot of money during the initial phase of the project." },
  { english: "acquisition", korean: "인수, 획득, 습득", sentence: "Dalefort Auto has diversified its business field through mergers and acquisitions." },
  { english: "impartially", korean: "공평하게, 편견 없이", sentence: "The most effective way to motivate employees is to evaluate them impartially." },
  { english: "favorable", korean: "호의적인, 유리한", sentence: "The city council offers entrepreneurs a favorable tax rate, making Windsor a great city in which to start a new business." },
  { english: "institute", korean: "기관, 협회, 설립하다", sentence: "The company plans to institute an Internet-based training course for new employees." },
  { english: "narrow", korean: "좁은, 불충분한, 좁히다", sentence: "The hiring committee narrowed down the applicants to 10." },
  { english: "terminate", korean: "종료하다, 끝내다", sentence: "Your contract of employment with the Royal Hotel will terminate in March." },
  { english: "confront", korean: "맞서다, 직면하다", sentence: "Unfortunately, the new operations center was confronted with a lack of raw materials." },
  { english: "alliance", korean: "제휴(관계), 동맹", sentence: "It is not easy for small start-up companies to make an alliance with other corporations." },
  { english: "specification", korean: "설명서, 사양", sentence: "All new recruits may refer to job specifications in the orientation packet." },
  { english: "compromise", korean: "타협하다, 타협, 절충", sentence: "They never compromise on quality standards." },
  { english: "affiliation", korean: "제휴, 협력, 소속", sentence: "We have an affiliation with the five-star hotel." },
  { english: "commission", korean: "제작을 의뢰하다, 수수료", sentence: "The noted sculptor has been commissioned to carve a statue." },
  { english: "contingency", korean: "우발 사건, 만일의 사태", sentence: "The company management should create adequate contingency plans." },

  // ── Day 9 ──────────────────────────────────────────────────
  { english: "earn", korean: "벌다, (평판을)얻다", sentence: "This project should earn enough money to go to the next one." },
  { english: "invest", korean: "투자하다", sentence: "The firm invested millions of dollars in buying a factory in China." },
  { english: "profit", korean: "이익, 수익", sentence: "We made a huge profit from the export of natural resources." },
  { english: "depend on", korean: "~에 달려 있다, 의존하다", sentence: "Many small and medium-sized businesses depend on bank loans." },
  { english: "due", korean: "(지불. 마감)기한이 된", sentence: "His orders failed to arrive by the expected due date on the order confirmation." },
  { english: "accomplished", korean: "기량이 뛰어난, 재주가 많은", sentence: "Ms. Parson has been promoted rapidly because she is an accomplished accountant." },
  { english: "reduce", korean: "줄이다, 감소시키다", sentence: "The accountant advised us to reduce unnecessary overhead costs." },
  { english: "outcome", korean: "결과, 성과", sentence: "We are expecting the positive outcome of the long-term negotiations with Blue Pacific." },
  { english: "share", korean: "주식, 몫, 나누다", sentence: "We should analyze our competitors' strategies to increase our market share." },
  { english: "income", korean: "소득, 수입", sentence: "Many coastal cities are reliant on tourism as a main source of income." },
  { english: "exchange", korean: "교환하다, 환전하다", sentence: "You can exchange the product within 14 days if it is defective." },
  { english: "gain", korean: "얻다, 증가, 이익", sentence: "To gain access to online content, simply register on our website." },
  { english: "rise", korean: "증가하다, 오르다, 증가", sentence: "The unemployment rate has steadily risen due to the recent economic recession." },
  { english: "exceed", korean: "초과하다, 넘어서다", sentence: "We have already exceeded initial earnings projections for this year." },
  { english: "largely", korean: "주로, 대체로, 크게", sentence: "This quarter's sales increase is largely due to the new line of clothing." },
  { english: "considerable", korean: "상당한", sentence: "Experts are concerned that there will be considerable changes in the cost of raw materials." },
  { english: "overcome", korean: "극복하다, 이기다", sentence: "The company may lay off workers to overcome the financial difficulties." },
  { english: "secure", korean: "안전한, 확보하다", sentence: "To secure a promising contract, the CEO is taking part in the conference." },
  { english: "forecast", korean: "예측하다, 예보, 예측", sentence: "Several financial institutions forecast a recovery in the economy." },
  { english: "appropriate", korean: "적절한, 적당한", sentence: "Mr. Musgrave reviewed the specific terms of the loan and signed the appropriate document." },
  { english: "bankrupt", korean: "파산한", sentence: "The company was bankrupted by an unexpected patent dispute." },
  { english: "double", korean: "두 배로 만들다, 두 배의", sentence: "According to last month's records, the sales figures have doubled." },
  { english: "optimistic", korean: "낙천적인, 긍정적인", sentence: "The marketing director is cautiously optimistic about the sales performance." },
  { english: "portion", korean: "부분, 일부", sentence: "The organization will donate a substantial portion of the profits to charity." },
  { english: "prosperous", korean: "번영하는, 성공하는", sentence: "With the success of our latest model, our company will be financially prosperous." },
  { english: "fund", korean: "자금을 지원하다, 기금", sentence: "The Cultural & Welfare Center is privately funded." },
  { english: "remarkable", korean: "놀라운, 주목할 만한", sentence: "The new marketing campaign led to a remarkable rise in sales." },
  { english: "duration", korean: "(지속되는)기간, 지속", sentence: "Mr. Karl has decided to rent a car for the duration of his trip in the US." },
  { english: "beneficial", korean: "유익한, 이로운", sentence: "Customers' feedback is very beneficial to us for multiple reasons." },
  { english: "obtain", korean: "얻다, 취득하다", sentence: "You need to fill out the form to obtain a copy of the balance sheet." },
  { english: "revenue", korean: "매출, 수입, 수익", sentence: "We invest 30% of our total revenue in R&D." },
  { english: "soar", korean: "급등하다, 증가하다", sentence: "Our production costs soared due to rises in labor costs and taxes." },
  { english: "lucrative", korean: "수익성이 좋은", sentence: "I'm going on a business trip to find a lucrative business idea." },
  { english: "dividend", korean: "배당금", sentence: "Setting manageable goals is an important step toward granting greater dividends to investors." },
  { english: "projection", korean: "추정(치), 예상(치)", sentence: "The program will help us make projections of future earnings." },
  { english: "embezzle", korean: "횡령하다", sentence: "Mr. Yamamoto, the former president, was charged with embezzling company funds." },
  { english: "bounce", korean: "(수표가)부도 처리되다", sentence: "If there is not enough money in your bank account, the check will bounce." },
  { english: "setback", korean: "차질, 좌절, 역행", sentence: "After the strike by engineers, GT motors suffered a huge setback." },
  { english: "adequate", korean: "적절한, 충분한", sentence: "This business strategy seems adequate in the present situation." },
  { english: "markedly", korean: "현저하게, 뚜렷하게", sentence: "Our annual revenues have markedly decreased because of severe competition." },

  // ── Day 10 ─────────────────────────────────────────────────
  { english: "asset", korean: "자산, 자산 가치가 있는 사람", sentence: "The firm will sell off some of its assets in order to resolve the financial crisis." },
  { english: "amount", korean: "총계가 ~에 이르다, 양, 액수", sentence: "The annual net profit amounts to one billion dollars." },
  { english: "cash", korean: "현금, 현찰로 지불하다", sentence: "Where can I cash a check?" },
  { english: "debt", korean: "빚, 부채", sentence: "Nearly half of the smaller businesses are suffering from high levels of debt." },
  { english: "accounting", korean: "회계(학)", sentence: "Mr. Park has a degree in accounting." },
  { english: "expense", korean: "비용, 경비", sentence: "Please keep the receipt to get reimbursed for travel expense." },
  { english: "sharply", korean: "급격히, 날카롭게", sentence: "The company's stock prices have sharply risen since it released the new product." },
  { english: "vary", korean: "다양하다, 다르다", sentence: "Please note that prices vary according to the quality of materials you require." },
  { english: "proceeds", korean: "수익금", sentence: "All proceeds from the benefit concert will go to local charities." },
  { english: "remain", korean: "남다, 계속~이다, 유지하다", sentence: "Despite the economic depression, our company still remains profitable." },
  { english: "outstanding", korean: "뛰어난, 현저한, 미결제된", sentence: "We hope to recruit many outstanding workers at the job fair." },
  { english: "profitable", korean: "수익성이 있는, 이로운", sentence: "We need to find a profitable way to make up for the trade deficit." },
  { english: "mark", korean: "표시하다, 자국, 흔적", sentence: "I marked red on the deficit for future reference." },
  { english: "modify", korean: "수정하다, 변경하다", sentence: "Considering the current market situation, our sales projection should be modified." },
  { english: "loss", korean: "손실(액), 손해", sentence: "The auditors discovered a substantial loss in the company's account." },
  { english: "steady", korean: "지속적인, 꾸준한", sentence: "The government's environmentally-friendly policy encourages steady growth in green industries." },
  { english: "quarter", korean: "분기, 4분의1", sentence: "Evergreen Insurance made record profits in the previous quarter." },
  { english: "raise", korean: "올리다, 모으다, 인상", sentence: "The labor union asked the management to raise salaries in the negotiations." },
  { english: "lower", korean: "낮추다, 내리다", sentence: "CRT Insurance lowered its annual profit projections again." },
  { english: "return", korean: "돌아오다, 반납, 수익", sentence: "It's almost impossible to get high rates of return these days." },
  { english: "venue", korean: "현장, 장소, 개최지", sentence: "I was told that the venue for the staff meeting changed all of a sudden." },
  { english: "accurate", korean: "정확한, 정밀한", sentence: "Make sure that the information is accurate before writing an analysis report." },
  { english: "fiscal", korean: "재정(상)의, 회계의", sentence: "The annual sales report will be delivered to the publisher by the end of this fiscal year." },
  { english: "convert", korean: "전환하다, 변환하다", sentence: "Employees are eligible to convert unused paid leave to cash." },
  { english: "constraint", korean: "제약", sentence: "Despite budget constraints, the government decided to increase salaries for all civil servants." },
  { english: "stable", korean: "안정적인, 견실한", sentence: "The stock holders hope that the company's financial status will remain stable for a while." },
  { english: "statistics", korean: "통계(학)", sentence: "An analysis of the statistics indicates that our net profit will reach one billion dollars next year." },
  { english: "credit", korean: "(공적을)~에게 돌리다, 신용", sentence: "Her success in business is credited to fierce determination." },
  { english: "spare", korean: "여분의, 할애하다", sentence: "Apparently our Boston branch holds spare funds amounting to three million dollars." },
  { english: "liable", korean: "책임 있는, 하기 쉬운", sentence: "The manufacturer is not liable for any damage caused by misuse." },
  { english: "deduct", korean: "공제하다, 빼다", sentence: "As of next month, your health insurance premium will be deducted from your wages." },
  { english: "capital", korean: "자금, 자산", sentence: "The biggest U.S. investment bank announced that they will raise capital for industry." },
  { english: "accrue", korean: "축적되다, (이자가)붙다", sentence: "The longer you take to repay your bank loan, the more interest will accrue." },
  { english: "offset", korean: "상쇄하다, 메우다", sentence: "We had to increase the prices to offset the increased production cost." },
  { english: "delinquent", korean: "연체된, 체납된", sentence: "Customers who had been delinquent in paying their bills will be charged a late fee." },
  { english: "audit", korean: "(회계)감사, 심사", sentence: "A tax audit was conducted without advance notice." },
  { english: "counterfeit", korean: "위조의, 모조의, 위조하다", sentence: "As soon as the signature was proven to be counterfeit, they canceled the contract." },
  { english: "deficit", korean: "적자, 결손", sentence: "The machinery breakdown caused the delay in production and it led to a heavy deficit." },
  { english: "appraise", korean: "(재산 등을)평가하다, 값을 매기다", sentence: "A real estate agent should know how to appraise the value of properties." },
  { english: "edge", korean: "우위, 유리함, 가장자리", sentence: "The competitive edge of this product lies in its high quality display." },
];
