const HOMEWORK1_VERSION = "v6";

const HOMEWORK1 = [
  { questionText: "The company plans to ________ its operations into Southeast Asia next year.", optionA: "expand", optionB: "expansion", optionC: "expansive", optionD: "expanded", answer: "A", explanation: "✅ A (expand) — 동사원형, plans to 뒤에 올바른 형태\n❌ B (expansion) — 명사: 동사 자리에 명사 불가\n❌ C (expansive) — 형용사: 동사 자리에 형용사 불가\n❌ D (expanded) — 과거/과거분사: to 뒤에는 동사원형 필요\n💡 [동사] + to + 동사원형 구조\nplans to, wants to, needs to, hopes to, intends to 모두 동일\n❗ to 뒤에는 반드시 동사원형!\n🔑 해석: 그 회사는 내년에 동남아시아로 사업을 확장할 계획입니다." },
  { questionText: "The new policy will ________ take effect starting next Monday.", optionA: "official", optionB: "officially", optionC: "officiate", optionD: "officials", answer: "B", explanation: "✅ B (officially) — 부사, 동사 take를 수식\n❌ A (official) — 형용사/명사: 동사를 수식할 수 없음\n❌ C (officiate) — 동사: will take가 이미 있어 동사 중복 불가\n❌ D (officials) — 명사: 동사 앞 자리는 부사\n💡 빈칸이 동사 앞·뒤에 있으면 → 부사 자리\nwill officially take effect (공식적으로 발효될 것이다)\nwas officially announced (공식적으로 발표되었다)\n🔑 해석: 새로운 정책은 다음 주 월요일부터 공식적으로 발효될 것입니다." },
  { questionText: "The ________ of the new software will begin next quarter.", optionA: "implement", optionB: "implementing", optionC: "implementation", optionD: "implemented", answer: "C", explanation: "✅ C (implementation) — 명사, 주어 자리\n❌ A (implement) — 동사: 관사(The) 뒤에는 명사 필요\n❌ B (implementing) — 동명사: The implementing of... 는 부자연스러운 표현\n❌ D (implemented) — 과거분사: 관사 뒤 주어 자리에 부적합\n💡 관사(The/A/An) 바로 뒤는 항상 명사 자리\nThe + 명사 + of + 명사 패턴: The implementation of(~의 도입), The announcement of(~의 발표)\n🔑 해석: 새 소프트웨어의 도입은 다음 분기에 시작될 것입니다." },
  { questionText: "The store will remain open ________ the holiday season.", optionA: "by", optionB: "until", optionC: "since", optionD: "throughout", answer: "D", explanation: "✅ D (throughout) — '~내내, ~전체에 걸쳐' 기간 전체 지속\n❌ A (by) — '~까지' 기한/마감 표현 (by 5 PM = 5시까지 완료)\n❌ B (until) — '~까지 계속' 지속 종료 시점 (open until 9 PM = 9시에 닫음)\n❌ C (since) — '~이래로' 시작점 (since 2020 = 2020년부터 지금까지)\n💡 throughout + 기간 = 그 기간 내내\nthroughout the day(하루 종일), throughout the year(일 년 내내)\n🔑 해석: 가게는 연휴 시즌 내내 영업할 것입니다." },
  { questionText: "Attendance at the training session is ________ for all new employees.", optionA: "mandatory", optionB: "mandate", optionC: "mandatorily", optionD: "mandated", answer: "A", explanation: "✅ A (mandatory) — 형용사 '의무적인', is 뒤 보어 자리\n❌ B (mandate) — 동사/명사: 동사면 is와 중복, 명사면 문맥 어색\n❌ C (mandatorily) — 부사: 보어 자리에 부사 불가\n❌ D (mandated) — 과거분사: is mandated for... 구조도 가능하나 보어로는 형용사가 자연스러움\n💡 be동사 + 형용사 보어: S + is/are + 형용사\ncompulsory(의무의) = mandatory = required(필수의) = obligatory\n🔑 해석: 훈련 세션 참석은 모든 신입 직원에게 의무입니다." },
  { questionText: "Customers can access their account information ________ the company website.", optionA: "throughout", optionB: "through", optionC: "though", optionD: "thorough", answer: "B", explanation: "✅ B (through) — '~을 통해' 수단/방법 표현\n❌ A (throughout) — '~전체에 걸쳐': throughout the company(회사 전체에) — 수단 아님\n❌ C (though) — 접속사 '비록 ~이지만': 뒤에 절(주어+동사) 필요\n❌ D (thorough) — 형용사 '철저한': a thorough investigation(철저한 조사)\n💡 수단 표현: through = via = by means of\nthrough the website(웹사이트를 통해), via email(이메일로)\n🔑 해석: 고객들은 회사 웹사이트를 통해 계정 정보에 접근할 수 있습니다." },
  { questionText: "The company offers ________ benefits to attract top talent.", optionA: "compete", optionB: "competition", optionC: "competitive", optionD: "competitively", answer: "C", explanation: "✅ C (competitive) — 형용사 '경쟁력 있는', 명사 benefits 수식\n❌ A (compete) — 동사: 명사 앞은 형용사 자리\n❌ B (competition) — 명사: 명사+명사 복합명사로 쓰이려면 자연스러운 조합이어야 함\n❌ D (competitively) — 부사: 부사는 명사를 수식할 수 없음\n💡 명사 앞 = 형용사 자리\ncompetitive salary(경쟁력 있는 급여), competitive price(경쟁력 있는 가격)\n🔑 해석: 그 회사는 최고의 인재를 유치하기 위해 경쟁력 있는 혜택을 제공합니다." },
  { questionText: "Employees should ________ their supervisors of any changes in their schedule.", optionA: "notice", optionB: "notification", optionC: "notable", optionD: "notify", answer: "D", explanation: "✅ D (notify) — 동사 '알리다', should 뒤 동사원형\n❌ A (notice) — '알아채다/공지': notice + 사람 + of 구조가 없음\n❌ B (notification) — 명사 '알림': should 뒤에는 동사원형 필요\n❌ C (notable) — 형용사 '주목할 만한': should 뒤에는 동사원형 필요\n💡 notify + 목적어(사람) + of + 내용\n= inform + 목적어 + of/about + 내용 (동일 의미)\n= alert + 목적어 + to + 내용 (동일 의미)\n🔑 해석: 직원들은 일정 변경 사항을 상사에게 알려야 합니다." },
  { questionText: "The ________ renovation of the lobby is expected to be completed by May.", optionA: "ongoing", optionB: "gone", optionC: "onward", optionD: "go", answer: "A", explanation: "✅ A (ongoing) — 형용사 '진행 중인', 명사 renovation 수식\n❌ B (gone) — 형용사 '사라진, 없어진': 의미상 부적절\n❌ C (onward) — 부사/형용사 '앞으로의': onward renovation은 어색한 표현\n❌ D (go) — 동사: 관사(The) 뒤 명사 수식 자리에 동사 불가\n💡 ongoing = in progress = currently happening\nongoing project(진행 중인 프로젝트), ongoing investigation(현재 진행 중인 조사)\n🔑 해석: 로비의 현재 진행 중인 보수 공사는 5월까지 완료될 예정입니다." },
  { questionText: "All employees are required to submit their reports ________ the end of the day.", optionA: "until", optionB: "by", optionC: "since", optionD: "during", answer: "B", explanation: "✅ B (by) — '~까지' 완료 기한 표현\n❌ A (until) — '~까지 계속': submit until은 계속 제출한다는 의미로 어색\n❌ C (since) — '~이래로' 시작점 (since Monday = 월요일 이후로 쭉)\n❌ D (during) — '~동안': during the end는 문법적으로 어색\n💡 by vs until 핵심 구분\n• by + 시점 = 마감/기한 (결과 완료)\n• until + 시점 = 지속 종료 시점 (행동 계속)\nSubmit by Friday.(금요일까지 완료) / Work until Friday.(금요일까지 계속 일함)\n🔑 해석: 모든 직원은 하루가 끝나기 전까지 보고서를 제출해야 합니다." },
  { questionText: "The ________ of the new store location will be announced next week.", optionA: "select", optionB: "selective", optionC: "selection", optionD: "selectively", answer: "C", explanation: "✅ C (selection) — 명사 '선택, 선정', 주어 자리\n❌ A (select) — 동사: 관사(The) 뒤에는 명사 필요\n❌ B (selective) — 형용사 '선별적인': The selective of... 는 비문법적\n❌ D (selectively) — 부사: 주어 자리에 부사 불가\n💡 The + 명사 + of + 명사 패턴\nThe selection of(~의 선정), The announcement of(~의 발표), The completion of(~의 완료)\n🔑 해석: 새 매장 위치 선정은 다음 주에 발표될 것입니다." },
  { questionText: "The proposal was ________ accepted by all members of the committee.", optionA: "unanimous", optionB: "unanimity", optionC: "unanimousness", optionD: "unanimously", answer: "D", explanation: "✅ D (unanimously) — 부사 '만장일치로', 동사 accepted 수식\n❌ A (unanimous) — 형용사: 동사 수식 불가 (명사 수식용: a unanimous decision)\n❌ B (unanimity) — 명사 '만장일치': 부사 자리에 명사 불가\n❌ C (unanimousness) — 명사: unanimity와 같은 의미지만 거의 사용 안 됨\n💡 was + 부사 + 과거분사 어순\nwas unanimously accepted(만장일치로 수락됨)\nwas officially announced(공식 발표됨)\nwas formally approved(공식 승인됨)\n🔑 해석: 그 제안은 위원회의 모든 구성원들에 의해 만장일치로 수락되었습니다." },
  { questionText: "The customer service team is ________ to resolving complaints within 24 hours.", optionA: "committed", optionB: "committing", optionC: "commit", optionD: "commitment", answer: "A", explanation: "✅ A (committed) — 과거분사, be committed to 관용 표현\n❌ B (committing) — 현재분사: is committing to는 의미 다름(위탁하고 있다)\n❌ C (commit) — 동사원형: is 다음에 동사원형 불가\n❌ D (commitment) — 명사: is commitment는 관용 표현 아님\n💡 be committed to + 동명사(-ing): ~에 전념하다\nbe dedicated to + -ing / be devoted to + -ing (같은 의미)\n❗ to 다음에 동명사(-ing)! to부정사의 to가 아님!\n🔑 해석: 고객 서비스 팀은 24시간 내에 불만을 해결하는 데 전념합니다." },
  { questionText: "Mr. Kim was promoted ________ his outstanding performance last year.", optionA: "despite", optionB: "because of", optionC: "although", optionD: "whereas", answer: "B", explanation: "✅ B (because of) — 전치사구 '~ 때문에', 뒤에 명사구\n❌ A (despite) — '~에도 불구하고': 문맥상 반대 의미 (성과에도 불구하고 승진?)\n❌ C (although) — 접속사: although + 주어 + 동사 (절 필요)\n❌ D (whereas) — 접속사 '반면에': 대조 의미 + 절 필요\n💡 이유 전치사 정리\n• because of + 명사구: ~ 때문에\n• due to + 명사구: ~ 때문에 (= because of)\n• owing to + 명사구: ~ 덕분에/때문에\n❗ because(접속사) vs because of(전치사) 구분!\n🔑 해석: 김 씨는 지난해의 뛰어난 성과 때문에 승진했습니다." },
  { questionText: "The technician will ________ the equipment before the factory resumes operations.", optionA: "inspection", optionB: "inspector", optionC: "inspect", optionD: "inspected", answer: "C", explanation: "✅ C (inspect) — 동사원형, will 뒤 올바른 형태\n❌ A (inspection) — 명사 '점검, 검사': will 다음에는 동사원형 필요\n❌ B (inspector) — 명사 '검사관': will 다음에는 동사원형 필요\n❌ D (inspected) — 과거형/과거분사: will + 과거형은 문법 오류\n💡 조동사 + 동사원형\nwill / can / should / must / may 다음에는 반드시 동사원형\nwill inspect(점검), will check(확인), will examine(검사), will review(검토)\n🔑 해석: 기술자는 공장이 운영을 재개하기 전에 장비를 점검할 것입니다." },
  { questionText: "The budget proposal needs ________ approval from the board of directors.", optionA: "finally", optionB: "finalize", optionC: "finality", optionD: "final", answer: "D", explanation: "✅ D (final) — 형용사 '최종의', 명사 approval 수식\n❌ A (finally) — 부사 '마침내': 부사는 명사를 수식할 수 없음\n❌ B (finalize) — 동사 '마무리 짓다': 명사 앞은 형용사 자리\n❌ C (finality) — 명사 '최종성': finality approval은 비표준 표현\n💡 명사 앞 형용사 자리 패턴: _______ + 명사\nfinal approval(최종 승인), formal approval(공식 승인), official approval(공식 승인)\n🔑 해석: 예산 제안서는 이사회로부터 최종 승인이 필요합니다." },
  { questionText: "Please ________ that all forms are completed before submission.", optionA: "ensure", optionB: "assure", optionC: "insure", optionD: "secure", answer: "A", explanation: "✅ A (ensure) — '~을 확실히 하다', ensure + that절 구조\n❌ B (assure) — '(사람을) 안심시키다': assure + 사람 + that절 (목적어가 사람)\n❌ C (insure) — '보험에 들다': 주로 금전적 보장 의미\n❌ D (secure) — '확보하다': secure + 명사 (that절 불가)\n💡 ensure / assure / insure 비교\n• ensure (that) ~: ~을 확실히 하다 ← TOEIC 최빈출\n• assure + 사람 + that ~: (사람을) 안심시키다\n• insure: 보험에 들다 (보험 맥락)\n🔑 해석: 제출 전에 모든 양식이 완성되어 있는지 확인해주세요." },
  { questionText: "The sales team exceeded its ________ target for the third consecutive quarter.", optionA: "annually", optionB: "annual", optionC: "annualize", optionD: "annualized", answer: "B", explanation: "✅ B (annual) — 형용사 '연간의', 명사 target 수식\n❌ A (annually) — 부사 '매년': 부사는 명사를 수식할 수 없음\n❌ C (annualize) — 동사 '연간으로 환산하다': 명사 앞 형용사 자리\n❌ D (annualized) — 과거분사/형용사 '연간화된': annual이 더 일반적\n💡 명사 target 앞 형용사 자리\nannual target(연간 목표), quarterly target(분기 목표), monthly target(월간 목표)\n관련 어휘: annual report(연간 보고서), annual salary(연봉)\n🔑 해석: 영업팀은 3분기 연속으로 연간 목표를 초과 달성했습니다." },
  { questionText: "The director will ________ the new recruits to their departments.", optionA: "assignment", optionB: "assigned", optionC: "assign", optionD: "assigning", answer: "C", explanation: "✅ C (assign) — 동사원형, will 뒤 올바른 형태\n❌ A (assignment) — 명사 '과제, 배정': will 다음에는 동사원형 필요\n❌ B (assigned) — 과거형/과거분사: will + 과거형은 문법 오류\n❌ D (assigning) — 현재분사: will 다음에 현재분사 불가\n💡 assign A to B = A를 B에 배정하다\n조동사 will 다음: will assign, will allocate, will place\n🔑 해석: 이사는 새 신입 사원들을 각 부서에 배정할 것입니다." },
  { questionText: "Employees who wish to take ________ leave must submit a request in advance.", optionA: "paying", optionB: "pay", optionC: "payment", optionD: "paid", answer: "D", explanation: "✅ D (paid) — 형용사/과거분사 '유급의', paid leave 고정 표현\n❌ A (paying) — 현재분사: paying leave는 '휴가를 지불하는'으로 의미 이상\n❌ B (pay) — 동사/명사: pay leave는 비표준 표현\n❌ C (payment) — 명사: payment leave는 사용하지 않는 표현\n💡 휴가 관련 필수 어휘\n• paid leave / paid vacation = 유급 휴가\n• unpaid leave = 무급 휴가\n• sick leave = 병가\n• maternity leave = 출산 휴가\n• annual leave = 연차\n🔑 해석: 유급 휴가를 사용하고자 하는 직원은 사전에 신청서를 제출해야 합니다." },
  { questionText: "Parking is available ________ the building on weekdays.", optionA: "behind", optionB: "beside", optionC: "between", optionD: "beneath", answer: "A", explanation: "✅ A (behind) — '~ 뒤에', 건물 뒤쪽 주차장 의미\n❌ B (beside) — '~ 옆에, 나란히': 건물 옆 주차장도 가능하나 문맥상 뒤쪽\n❌ C (between) — '~ 사이에': 두 개의 대상 사이에 사용 (between A and B)\n❌ D (beneath) — '~ 아래에': 지하 주차장이면 가능하나 본문에서는 behind가 적합\n💡 위치 전치사 총정리\n• in front of: ~앞에 | behind: ~뒤에\n• beside / next to: ~옆에 | between: ~사이에(둘)\n• among: ~중에(셋 이상) | beneath/under: ~아래에\n🔑 해석: 주차는 주중에 건물 뒤에서 가능합니다." },
  { questionText: "The ________ speaker at the conference impressed the audience with her insights.", optionA: "key", optionB: "keynote", optionC: "keenly", optionD: "keen", answer: "B", explanation: "✅ B (keynote) — '기조의', keynote speaker = 기조연설자 (고정 표현)\n❌ A (key) — '핵심적인': key speaker도 쓰이나 TOEIC에서는 keynote speaker가 정답\n❌ C (keenly) — 부사 '예리하게': 부사는 명사를 수식할 수 없음\n❌ D (keen) — 형용사 '열심인': keen speaker = 열정적인 연설자 (의미 다름)\n💡 TOEIC 고빈도 복합명사\nkeynote speaker(기조연설자), keynote address(기조연설)\nannual conference(연례 컨퍼런스), opening ceremony(개막식)\n🔑 해석: 컨퍼런스의 기조연설자는 자신의 통찰로 청중을 감동시켰습니다." },
  { questionText: "The factory is operating at full ________ to meet holiday demand.", optionA: "capable", optionB: "capably", optionC: "capacity", optionD: "capability", answer: "C", explanation: "✅ C (capacity) — 명사 '용량, 생산 능력', at full capacity 관용 표현\n❌ A (capable) — 형용사 '능력 있는': at full capable은 비문법적\n❌ B (capably) — 부사 '유능하게': at full capably는 비문법적\n❌ D (capability) — 명사 '역량': at full capability도 사용하나 capacity가 생산/운영 맥락에서 표준\n💡 capacity 관련 표현\n• at full capacity = 최대 가동으로, 풀가동\n• production capacity = 생산 능력\n• seating capacity = 좌석 수\n• beyond capacity = 정원 초과\n🔑 해석: 공장은 연휴 수요를 충족하기 위해 풀가동으로 운영 중입니다." },
  { questionText: "The ________ survey results will be shared with all department heads.", optionA: "lately", optionB: "late", optionC: "later", optionD: "latest", answer: "D", explanation: "✅ D (latest) — 형용사 '가장 최신의', 명사 results 수식\n❌ A (lately) — 부사 '최근에': 부사는 명사 수식 불가 (I haven't seen him lately)\n❌ B (late) — 형용사 '늦은': late results = 늦게 나온 결과 (의미 다름)\n❌ C (later) — 형용사/부사 '나중의': later results = 나중에 나올 결과 (미래 의미)\n💡 late 계열 단어 비교\n• late: 늦은 (a late arrival)\n• lately: 최근에 (부사, 현재완료와 자주 사용)\n• later: 나중에/더 늦은\n• latest: 가장 최신의 (최상급)\n🔑 해석: 최신 설문 결과는 모든 부서장들과 공유될 것입니다." },
  { questionText: "The client requested that the report be submitted ________ Friday morning.", optionA: "by", optionB: "on", optionC: "at", optionD: "in", answer: "A", explanation: "✅ A (by) — '~까지' 기한/마감 표현\n❌ B (on) — 특정 날짜/요일: on Friday(금요일에) — 기한 아님\n❌ C (at) — 특정 시각: at 9 AM(오전 9시에) — 날짜와 사용 불가\n❌ D (in) — '~안에, ~후에': in the morning(오전에), in two days(이틀 후)\n💡 시간 전치사 총정리\n• at + 시각: at 3 PM | on + 날짜/요일: on Monday\n• in + 연도/월/계절: in 2024, in July | by + 기한: by Friday\n🔑 해석: 고객은 보고서가 금요일 오전까지 제출되기를 요청했습니다." },
  { questionText: "The human resources department is ________ for processing all job applications.", optionA: "responsive", optionB: "responsible", optionC: "respective", optionD: "reluctant", answer: "B", explanation: "✅ B (responsible) — '담당하는, 책임 있는', be responsible for 관용 표현\n❌ A (responsive) — '반응하는': be responsive to(~에 반응하다) — 전치사 to와 사용\n❌ C (respective) — '각자의, 각각의': their respective roles(각자의 역할) — for 뒤에 오지 않음\n❌ D (reluctant) — '꺼리는': be reluctant to do(~하기를 꺼리다) — 의미 전혀 다름\n💡 be responsible for + 명사/동명사 = ~을 담당하다\nbe in charge of = be accountable for (같은 의미)\n🔑 해석: 인사부는 모든 입사 지원서를 처리하는 것을 담당합니다." },
  { questionText: "The conference room is ________ available for booking after 3 P.M.", optionA: "ever", optionB: "already", optionC: "only", optionD: "yet", answer: "C", explanation: "✅ C (only) — 부사 '오직, ~만', 제한/조건 표현\n❌ A (ever) — '언제나, 한 번이라도': is ever available = 언제든 예약 가능 (의미 반대)\n❌ B (already) — '이미': is already available = 이미 예약 가능 (시제상 어색)\n❌ D (yet) — '아직': is yet available = 아직 예약 가능 (not yet = 아직 불가)\n💡 only의 위치와 의미\n• Only John came. (존만 왔다)\n• only available after 3 PM (오후 3시 이후에만 이용 가능)\nonly = just = exclusively (오직, 단지)\n🔑 해석: 회의실은 오후 3시 이후에만 예약이 가능합니다." },
  { questionText: "The committee will ________ a new policy on remote work next month.", optionA: "introduction", optionB: "introducing", optionC: "introduced", optionD: "introduce", answer: "D", explanation: "✅ D (introduce) — 동사원형, will 뒤 올바른 형태\n❌ A (introduction) — 명사 '소개, 도입': will 다음에는 동사원형 필요\n❌ B (introducing) — 현재분사: will + 현재분사 불가 (be + -ing = 진행형)\n❌ C (introduced) — 과거형/과거분사: will + 과거형은 비문법적\n💡 조동사 will + 동사원형\nwill introduce(도입), will announce(발표), will implement(시행), will roll out(출시)\n🔑 해석: 위원회는 다음 달 재택근무에 관한 새 정책을 도입할 것입니다." },
  { questionText: "Staff members are encouraged to take ________ breaks throughout the workday.", optionA: "regular", optionB: "regularly", optionC: "regulate", optionD: "regulation", answer: "A", explanation: "✅ A (regular) — 형용사 '규칙적인', 명사 breaks 수식\n❌ B (regularly) — 부사 '규칙적으로': 부사는 명사 수식 불가 (take breaks regularly)\n❌ C (regulate) — 동사 '규제하다': 형용사 자리에 동사 불가\n❌ D (regulation) — 명사 '규정, 규제': regulation breaks는 어색한 표현\n💡 명사 앞 형용사 자리\nregular breaks(규칙적인 휴식), short breaks(짧은 휴식), frequent breaks(자주 하는 휴식)\n🔑 해석: 직원들은 근무 시간 내내 규칙적인 휴식을 취하도록 권장됩니다." },
  { questionText: "The factory agreed to ________ all defective products at no extra charge.", optionA: "replacement", optionB: "replace", optionC: "replacing", optionD: "replaced", answer: "B", explanation: "✅ B (replace) — 동사원형, agreed to 뒤 올바른 형태\n❌ A (replacement) — 명사 '교체, 대체품': to 뒤에는 동사원형 필요\n❌ C (replacing) — 동명사: agree to + 동명사 형태는 비표준\n❌ D (replaced) — 과거형/과거분사: to + 과거형 불가\n💡 agree to + 동사원형 = ~하기로 동의하다\npromise to / decide to / plan to / offer to (모두 동일 구조)\nreplace A with B = A를 B로 교체하다\n🔑 해석: 공장은 추가 비용 없이 모든 불량 제품을 교체하기로 동의했습니다." },
];

export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    if (!process.env.DATABASE_URL) {
      process.env.DATABASE_URL = "file:/app/dev.db";
    }
    const { PrismaClient } = await import("@prisma/client");
    const prisma = new PrismaClient();

    try {
      const FOREVER = new Date("9999-12-31T00:00:00.000Z");
      const TARGET_USERS = [
        { email: "dlsdn0420@naver.com", role: "ADMIN" },
        { email: "gugua35@naver.com", role: "VIEWER" },
        { email: "sohee@yeosintoeic.com", role: "MANAGER" },
      ];

      for (const u of TARGET_USERS) {
        const result = await prisma.user.updateMany({
          where: { email: u.email },
          data: { role: u.role, plan: "ALL", planExpiresAt: FOREVER },
        });
        if (result.count > 0) console.log(`[seed] ${u.email} → ${u.role}`);
      }

      // 모든 문제 빈칸 마커 교체 (------- → ________)
      const markerRow = await prisma.setting.findUnique({ where: { key: "blank_marker_v" } });
      if (markerRow?.value !== "2") {
        await prisma.$executeRaw`UPDATE "Question" SET "questionText" = REPLACE("questionText", '-------', '________')`;
        await prisma.setting.upsert({
          where: { key: "blank_marker_v" },
          update: { value: "2" },
          create: { key: "blank_marker_v", value: "2" },
        });
        console.log("[seed] 전체 문제 빈칸 마커 교체 완료");
      }

      // 버전이 다르면 숙제 문제 교체
      const versionRow = await prisma.setting.findUnique({ where: { key: "homework1_version" } });
      if (versionRow?.value !== HOMEWORK1_VERSION) {
        await prisma.question.deleteMany({ where: { homeworkSet: 1 } });
        await prisma.question.createMany({
          data: HOMEWORK1.map((q, i) => ({ part: 5, category: "homework", homeworkSet: 1, homeworkOrder: i + 1, ...q })),
        });
        await prisma.setting.upsert({
          where: { key: "homework1_version" },
          update: { value: HOMEWORK1_VERSION },
          create: { key: "homework1_version", value: HOMEWORK1_VERSION },
        });
        console.log(`[seed] 숙제 1번 ${HOMEWORK1.length}개 교체 완료 (${HOMEWORK1_VERSION})`);
      }
    } catch (e) {
      console.error("[seed] 오류 (서버는 계속 시작):", e);
    } finally {
      await prisma.$disconnect();
    }
  }
}
